export const TIKTOK_FONTS = [
    { name: "Poppins", value: "Poppins, sans-serif", category: "Trendy" },
    { name: "Montserrat", value: "Montserrat, sans-serif", category: "Bold" },
    { name: "Bebas Neue", value: "Bebas Neue, sans-serif", category: "Impact" },
    { name: "Oswald", value: "Oswald, sans-serif", category: "Strong" },
    { name: "Anton", value: "Anton, sans-serif", category: "Heavy" },
    { name: "Bangers", value: "Bangers, sans-serif", category: "Comic" },
    { name: "Righteous", value: "Righteous, sans-serif", category: "Bold" },
    { name: "Fredoka One", value: "Fredoka One, sans-serif", category: "Playful" },
    { name: "Bungee", value: "Bungee, sans-serif", category: "Funky" },
    { name: "Monoton", value: "Monoton, sans-serif", category: "Retro" },
    { name: "Creepster", value: "Creepster, cursive", category: "Spooky" },
    { name: "Orbitron", value: "Orbitron, sans-serif", category: "Futuristic" },
    { name: "Lobster", value: "Lobster, cursive", category: "Script" },
    { name: "Pacifico", value: "Pacifico, cursive", category: "Fun" },
    { name: "Dancing Script", value: "Dancing Script, cursive", category: "Elegant" },
    { name: "Kalam", value: "Kalam, cursive", category: "Handwritten" },
    { name: "Permanent Marker", value: "Permanent Marker, cursive", category: "Marker" },
    { name: "Shadows Into Light", value: "Shadows Into Light, cursive", category: "Casual" },
    { name: "Amatic SC", value: "Amatic SC, cursive", category: "Sketchy" },
    { name: "Caveat", value: "Caveat, cursive", category: "Handwriting" },
    { name: "Satisfy", value: "Satisfy, cursive", category: "Stylish" },
    { name: "Courgette", value: "Courgette, cursive", category: "Smooth" },
    { name: "Russo One", value: "Russo One, sans-serif", category: "Tech" },
    { name: "Bungee Shade", value: "Bungee Shade, sans-serif", category: "3D" },
    { name: "Shrikhand", value: "Shrikhand, cursive", category: "Decorative" },
    // Adding more TikTok-style viral fonts
    { name: "Rubik Glitch", value: "Rubik Glitch, sans-serif", category: "Glitch" },
    { name: "Abril Fatface", value: "Abril Fatface, display", category: "Bold Display" },
    { name: "Lilita One", value: "Lilita One, cursive", category: "Chunky" },
    { name: "Londrina Outline", value: "Londrina Outline, cursive", category: "Outline" },
    { name: "Bungee Inline", value: "Bungee Inline, cursive", category: "Inline" },
    { name: "Nabla", value: "Nabla, display", category: "3D Effect" },
    { name: "Teko", value: "Teko, sans-serif", category: "Modern" },
    { name: "Press Start 2P", value: "Press Start 2P, cursive", category: "Gaming" },
    { name: "Chela One", value: "Chela One, cursive", category: "Quirky" },
    { name: "Bungee Hairline", value: "Bungee Hairline, cursive", category: "Thin" },
    { name: "Faster One", value: "Faster One, cursive", category: "Speed" },
    { name: "Rubik Moonrocks", value: "Rubik Moonrocks, sans-serif", category: "Textured" },
    { name: "Rubik Wet Paint", value: "Rubik Wet Paint, cursive", category: "Graffiti" },
    { name: "Tourney", value: "Tourney, display", category: "Sports" },
    { name: "Zen Tokyo Zoo", value: "Zen Tokyo Zoo, display", category: "Distorted" }
]
